theme: jekyll-theme-minimal
title: Jacob Shapiro<br>                                                                                         
description: Incoming Software Engineer Intern @ Microsoft <br>Amherst College Class of 2022
logo: smallFileSquare.png
