theme: jekyll-theme-architect
title: Jacob Shapiro<br>                                                                                         
description: Incoming Software Engineer Intern @ Microsoft <br><br>Amherst College Class of 2022
logo: files/smallFileSquare.png
