theme: jekyll-theme-minimal
title: Jacob Shapiro<br>                                                                                         
description: Incoming Software Engineer @ Microsoft <br><br>Amherst College Class of 2022
logo: files/smallFileSquare.png
